FROM elixir:1.9.4-alpine

ENV MIX_ENV=test

WORKDIR /app

RUN apk add inotify-tools && \
  mix local.hex --force && \
  mix local.rebar --force

COPY mix.exs mix.lock ./

RUN mix do deps.get, compile

COPY . .

RUN mix compile
