version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - .:/app
    depends_on:
      - frontend
      - postgres

  frontend:
    build:
      context: ./assets
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - ./assets:/app
      - ./deps:/app/deps
      - ./priv:/app/priv

  postgres:
    image: postgres:12.0
    environment:
      POSTGRES_DB: kendrick_dev
    volumes:
      - ./.postgres_data:/var/lib/postgresql/data
