version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: ./scripts/dev/setup.sh
    tty: true
    ports:
      - "4000:4000"
    volumes:
      - deps:/app/deps
    depends_on:
      - postgres
      - frontend

  frontend:
    build:
      context: ./assets
      dockerfile: Dockerfile.dev
    tty: true
    volumes:
      - deps:/app/deps

  postgres:
    image: postgres:12.0
    environment:
      POSTGRES_DB: kendrick_dev

volumes:
  deps:
