version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.test
      cache_from:
        - "docker.pkg.github.com/${GITHUB_USERNAME}/kendrick_app/kendrick_app_web:latest"
    depends_on:
      - postgres

  postgres:
    image: postgres:12.0
