FROM elixir:1.9.4-alpine

WORKDIR /app

RUN apk add inotify-tools && \
  mix local.hex --force && \
  mix local.rebar --force

COPY mix.exs mix.lock ./
COPY config config

RUN mix deps.get && mix deps.compile

COPY . .
RUN mix compile
